### ISSUE TITLE
Error while using getData

### ISSUE THREAD

**Issue by 123saga** [jburkhardt/RAdwords#50] opened 2016-07-22 05:31 UTC
I am recieving the following error while using get data, same query used work previously, is there is any thing changed in RAdwords package.

`<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><reportDownloadError><ApiError><type>ReportDownloadError.MISSING_PARAMETER</type><trigger>Missing report definition</trigger><fieldPath></fieldPath></ApiError></reportDownloadError>`

**Comment by jburkhardt** [comment] 2016-07-22 08:03
Please provide:
- Operating System
- R Version
- RAdwords version
- the R code which leads to the error
- code as text rather than screenshots

**Comment by 123saga** [comment] 2016-07-22 15:57
sorry my question was incomplete, please find the details
Operating System: Windows 7
R Version: 3.2.2
RAdwords version: 0.1.9
the R code which leads to the error
   
```
   CPA_Query <- statement(select=c('Device','Cost','Conversions','CrossDeviceConversions','AllConversions'), 
                          report="CAMPAIGN_PERFORMANCE_REPORT", start=sdate, end=edate ,
                          where = where_caluse)
   CPA_data<-getData(clientCustomerId=clientCustomerId,
                     google_auth=google_auth,
                     statement=CPA_Query,includeZeroImpressions=TRUE)
```

**Comment by jburkhardt** [comment] 2016-07-25 07:13
There is a new RAdwords version 0.1.10. Could you please update the package.

I guess there is something wrong with ```where_clause```.  Please use ```AND```  in capital letters instead of ```and```. The same counts for ```IN```.

Moreover you have to put any strings in quotation mark like ```SEARCH'```
paste0("ConversionValue>0 and AllConversionValue> 0 and AdvertisingChannelType='SEARCH'")

I cannot reproduce the part with the campaign_list.

Hope that helps.

**Comment by 123saga** [comment] 2016-07-27 00:39
Hi @jburkhardt , sorry for not getting back to you sooner, looks there was some issue with my campaign list in the where clause, campaign list contains 340 campaigns, do you see any problem with this.

It worked with 
`paste0("ConversionValue>0 AND AllConversionValue> 0 AND AdvertisingChannelType='SEARCH'")
`

**Comment by jburkhardt** [comment] 2016-07-27 08:07
As long as I do not know what the object ```campaign_list``` exactly looks like, I can not help you any further.  
I suggest you download all campaigns and subset the data within R. Something like this might work for you:
```
campaign_list <- c('123546','234567','345678')
where_clause <- paste0("ConversionValue>0 AND AllConversionValue> 0 AND AdvertisingChannelType='SEARCH'")

CPA_Query <- statement(select=c('Device','Cost','Conversions','CrossDeviceConversions','AllConversions','CampaignId'), 
                          report="CAMPAIGN_PERFORMANCE_REPORT", start=sdate, end=edate ,
                          where = where_caluse)
CPA_data<-getData(clientCustomerId=clientCustomerId,
                     google_auth=google_auth,
                     statement=CPA_Query,includeZeroImpressions=TRUE)
CPA_data <- subset(CPA_data, CampaignId %in% campaign_list)
```

I hope you can go along with this.
As your problem is no issue with the RAdwords package per se, I will close this issue by now.

**Closed by jburkhardt** 2016-07-27 08:07 UTC

**Comment by 123saga** [comment] 2016-07-27 18:51
that make sense, I am doing the same thing, filtering data once i will for all the campaigns
