### ISSUE TITLE
Warning Message in readlines when trying getData

### ISSUE THREAD

**Issue by vishal14995** [jburkhardt/RAdwords#113] opened 2019-06-04 11:29 UTC
When trying to fetch reports with getData, the following error shows up:

Warning message:
In readLines(con <- gzfile(tmp), encoding = "UTF-8") : incomplete final line found on '~\AppData\Local\Temp\Rtmpg3qD1x\file2b6037793ff0'

I was wondering if it is because of the recent addition of UTF-8 encoding?

**Comment by jburkhardt** [comment] 2019-06-18 13:29
@vishal14995 Is it an error or only a warning message? Does `getData` return the data you want to fetch?
Moreover, what is your:
- OS
- R Version
- RAdwords version? Did you install RAdwords from GitHub or from CRAN?

**Comment by ciber2009** [comment] 2019-07-16 13:02
I have a similar problem and it does not return the data.
Warning message:
In readLines(con <- gzfile(tmp)) :
  incomplete final line found on 'C:\Users\C3218358\AppData\Local\Temp\RtmpQ39uf3\file15402775348'

**Comment by thiagomymetric** [comment] 2019-10-16 02:19
This happens cause developer token is not approved yet (I think), cause I am getting a XML with this message: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><reportDownloadError><ApiError><type>QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED</type><trigger>&lt;null&gt;</trigger><fieldPath></fieldPath></ApiError></reportDownloadError>

**Comment by mayoracek** [comment] 2020-04-06 14:23
Hello guys, please did you find the reason for this issue? Is it due to not yet approved token as I think that we have it approved. 

And have the same error.

data_query_test <- getData(clientCustomerId=client_id, google_auth = google_oauth, statement = searchterms_body, transformation = FALSE)
Warning message:
In readLines(con <- gzfile(tmp)) :
  incomplete final line found on 'C:\Users\User\AppData\Local\Temp\Rtmp06yI7q\file3cc0523d75ce

**Comment by mayoracek** [comment] 2020-04-06 14:26
Ah yeah, seem it is the developer token approval

**Comment by jburkhardt** [comment] 2020-04-08 15:36
Unfortunately, it is not possible to reproduce your issue without the exact code. As far as I know there is no error with the package. Please proof me wrong otherwise :) From the discussion above I assume that your issue is related to wrong developer settings inside the Google Ads account. For this reason I would like to close the issue.

**Comment by mayoracek** [comment] 2020-04-08 20:10
Hi!

sure i figured jt out it is issue with developer token!

lets close it 👍

**Comment by egkasatkin** [comment] 2021-03-04 06:39
I have this promblem and found a solution

I'm using combine account_id c("1",2","3","4") and in this case a have same problem

Just delete Cran version of package and install from github
require(devtools)
install_github('jburkhardt/RAdwords')

**Comment by jburkhardt** [comment] 2021-06-03 13:54
@AdamJayJonca Thank you for your message. If you want to download data from multiple ads accounts please follow the instructions here: https://jburkhardt.github.io/RAdwords/faq/#list-account-ids

**Closed by jburkhardt** 2021-06-03 13:54 UTC
